### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by trojikman** [itpp-labs/sync-addons#130]
Customer's feedback:

> If you can create documentation, please add more description on fields in Models screen :
> 
> - Call Public methods via API ​--> not clear
> 
> - Restrict Public methods ​--> not clear
> 
> - Allow Private methods ​--> not clear

Also many of the steps in the documentation are not obvious and are confusing, at least in 13.0.
We should add an example of using api applying curl.

**Comment by yelizariev** [comment]
Did the customer check doc/index.rst ?

**Comment by trojikman** [comment]
> Did the customer check doc/index.rst ?

Not sure, but there are no descriptions of the specified fields, only usage
