### ISSUE TITLE
openapi: mandatory field is not set [tested in 13.0]

### ISSUE THREAD

**Issue by trojikman** [itpp-labs/sync-addons#133]
I tried to follow instruction to create new integration and encountered an error in step "Set **Creation Context Presets**" from doc/index.rst
![Screenshot from 2020-04-23 17-32-21](https://user-images.githubusercontent.com/23641186/80126150-1c118200-85ac-11ea-8d1f-888499eec954.png)

**Comment by yelizariev** [comment]
Some analysis of the problem:

Odoo tries to create ``openapi.access.create.context``, which has required field ``model_id``. To avoid that the context record must be created at the same time as ``openapi.access`` is created. This should be done the same way as ``sale.order`` and ``sale.order.line`` work.

The update is supposed to be done somewhere here:

https://github.com/itpp-labs/sync-addons/blob/7b797cf1d6997d5d533f5984b8bcb6c6e6e10099/openapi/views/openapi_view.xml#L120-L130

**Comment by trojikman** [comment]
Fixed for 13.0 in #138

**Comment by trojikman** [comment]
Fixed for 12.0 in #139

**Comment by trojikman** [comment]
Fixed for 11.0 in #140

**Comment by trojikman** [comment]
Fixed for 10.0 in #141
