### ISSUE TITLE
openapi.group_user: cannot create log records

### ISSUE THREAD

**Issue by yelizariev** [itpp-labs/sync-addons#136]
Either use ``sudo()`` in ``create_log_record`` or grant ``create`` access.

**Comment by yelizariev** [comment]
I'd prefer to use sudo() to prevent making fake logs by malicous user

**Comment by yelizariev** [comment]
sudo() or SUPERUSER_ID

**Comment by yelizariev** [comment]
Steps:

* make a user with Openapi > User access
* send any request

**Comment by trojikman** [comment]
Anvar did it through granting access. I added Roadmap item about it in 13.0
