### ISSUE TITLE
[v12] openapi - keep getting 405 error 

### ISSUE THREAD

**Issue by kalmenchia** [itpp-labs/sync-addons#153]
Hi,

i am using V12 , openapi module but 
after installed and tried, it kept throwing ,
 "OPTIONS /api/v1/my_test_namespace/res.users/1 HTTP/1.1" 405 - 2 0.008 0.016

not sure what went wrong, i have tried to put the openapi
at my config file in the server_wide_modules = ... , which is the same as load= 
at command line right?

and module installed and configured but it seems that not working when 
i tried at editor.swagger.io with the token copied from my
user's OpenAPI Token or at the integrations, Identification token.

appreciate any advice.
thanks.

**Comment by yelizariev** [comment]
This section of the docs should help:

https://github.com/itpp-labs/sync-addons/blob/a9ea82388ff8ff56abcc5556f7f0cc7b213018e2/openapi/doc/index.rst#swagger-editor

**Comment by trojikman** [comment]
Feel free to reopen it if you have more questions
