### ISSUE TITLE
openapi: allow passing context to PATCH methods

### ISSUE THREAD

**Issue by yelizariev** [itpp-labs/sync-addons#154]
Places for updates:

* https://github.com/itpp-labs/sync-addons/blob/4cba92553737bfbd0f29016201455936b8e36ee9/openapi/controllers/pinguin.py#L683-L684
* https://github.com/itpp-labs/sync-addons/blob/4cba92553737bfbd0f29016201455936b8e36ee9/openapi/models/openapi_access.py#L410-L414

**Comment by trojikman** [comment]
Тут можно закрывать?

**Comment by yelizariev** [comment]
Да, сделано в #155
