### ISSUE TITLE
Superadmin user loses access to Apps and Settings menu

### ISSUE THREAD

**Issue by Ramil-Mukhametzyanov** [itpp-labs/sync-addons#169]
Create an OpenAPI by demo
Make sure that only the demo user is allowed to use the OpenAPI.
Edit an OpenAPI by Admin
Result: admin and superuser loses access to the Apps and Settings menu

Sorry, you are not allowed to modify documents of type 'Integration' (openapi.namespace). This operation is allowed for the groups:
  - OpenAPI/Manager - (Operation: write, User: 6)

Sorry, you are not allowed to access documents of type 'Module' (ir.module.module). This operation is allowed for the groups:
  - Administration/Settings - (Operation: read, User: 6)

**Comment by yelizariev** [comment]
What do you mean by ``Edit an OpenAPI by Admin`` ?
