### ISSUE TITLE
found extra "\n" at penguin  def controller_method_wrapper(*iargs, **ikwargs):

### ISSUE THREAD

**Issue by kalmenchia** [itpp-labs/sync-addons#178]
Hi , not sure is the issue where i found that extra "\n" character at ikwargs , so after removed the extra characters
the openapi , read for multi/single is working again.

**Comment by yelizariev** [comment]
Hi, I don't quite understand. Can you edit the file and make a pull request (you can do it via github ui: https://github.com/itpp-labs/sync-addons/edit/13.0/openapi/controllers/pinguin.py )
