### ISSUE TITLE
sync: updates backport

### ISSUE THREAD

**Issue by yelizariev** [itpp-labs/sync-addons#226]
From https://github.com/itpp-labs/sync-addons/pull/216 we have to backport following updates:

#  13.0 only:

Following updates are already in v12

* add helpers for one2one synchronization
*  sync: show icon in app switcher in Odoo EE
*  sync: allow empty values for project.eval_context

# 12.0 and 13.0

*  sync: add tokens for incoming webhooks
* sync: export xml: add missed webhook_type field
* sync: allow run without telegram package installed

**Comment by yelizariev** [comment]
- [ ] https://github.com/itpp-labs/sync-addons/pull/247
- [ ] https://github.com/itpp-labs/sync-addons/pull/249

**Comment by mentalko** [comment]
v12.0

sync: allow run without telegram package installed d0a3b9232fc5efe13290c065cc137f235093d802 уже есть эти изменения в 12 ветке
sync: export xml: add missed webhook_type field 18720a38e6889741bfab726215fa5f8957746244
sync: add tokens for incoming webhooks 69dc9c3d0e8081e36bbb67f0948f167f702fdc07
(#247) sync: Export Xml: add filter_domain field d83a082a161d878583da7928d83f8828f69ea099
(#249) zap a new type of parameters for cases when we need the possibility to …  c97c8c620d4dd81acaed140fa55cd521d2a2b2a0
(#249) added the possibility to fully duplicate the project 1a39a45fb4952350f91e6c0f3710ad4f78c14a6f

v13.0

sync: allow run without telegram package installed d0a3b9232fc5efe13290c065cc137f235093d802
sync: export xml: add missed webhook_type field 18720a38e6889741bfab726215fa5f8957746244
+sync: allow empty values for project.eval_context 6df763ddb4c3b74b1c448733838db2960d61d75a
+sync: show icon in app switcher in Odoo EE bb5a1706ac361a72240b58af31b67575e23beb45
+sync: add helpers for one2one synchronization 1bcfa177cb5dad14d38710bfa6ec2bc067097dcb
sync: add tokens for incoming webhooks 69dc9c3d0e8081e36bbb67f0948f167f702fdc07
(#247) sync: Export Xml: add filter_domain field d83a082a161d878583da7928d83f8828f69ea099
(#249) zap a new type of parameters for cases when we need the possibility to …  c97c8c620d4dd81acaed140fa55cd521d2a2b2a0
(#249) added the possibility to fully duplicate the project 1a39a45fb4952350f91e6c0f3710ad4f78c14a6f

**Comment by mentalko** [comment]
https://github.com/itpp-labs/sync-addons/pull/274
https://github.com/itpp-labs/sync-addons/pull/275
