### ISSUE TITLE
telegram lib

### ISSUE THREAD

**Issue by yelizariev** [itpp-labs/sync-addons#232]
Version must be 

git+https://github.com/python-telegram-bot/python-telegram-bot.git@v12.8

because latest doesn't work with python 3.5
```
odoo_1  |   File "/opt/odoo/custom/src/odoo/odoo/modules/module.py", line 82, in load_module
odoo_1  |     exec(open(modfile, 'rb').read(), new_mod.__dict__)
odoo_1  |   File "<string>", line 3, in <module>
odoo_1  |   File "/opt/odoo/auto/addons/sync/models/__init__.py", line 4, in <module>
odoo_1  |     from . import sync_project_demo
odoo_1  |   File "/opt/odoo/auto/addons/sync/models/sync_project_demo.py", line 10, in <module>
odoo_1  |     from telegram import Bot, Update
odoo_1  |   File "/usr/local/lib/python3.5/site-packages/telegram/__init__.py", line 21, in <module>
odoo_1  |     from .base import TelegramObject
odoo_1  |   File "/usr/local/lib/python3.5/site-packages/telegram/base.py", line 42
odoo_1  |     _id_attrs: Tuple[Any, ...] = ()
```

The version must be set in DINAR https://github.com/itpp-labs/sync-addons/blob/13.0/.DINAR/image/dependencies/pip.txt
(v12 at least)

Plus we have to make a note in installation instruction of Sync Studio.

Ideally, we need to switch to this lib instead https://github.com/eternnoir/pyTelegramBotAPI

**Comment by trojikman** [comment]
Can we close it?

**Comment by yelizariev** [comment]
> Ideally, we need to switch to this lib instead https://github.com/eternnoir/pyTelegramBotAPI

We should switch to another lib, then this issue could be closed :slightly_smiling_face:

**Comment by yelizariev** [comment]
I made a new issue for this: https://github.com/itpp-labs/sync-addons/issues/295
