### ISSUE TITLE
sync: forward port updates from v12

### ISSUE THREAD

**Issue by yelizariev** [itpp-labs/sync-addons#233]
- [x] All commits for ``sync`` module from this PR https://github.com/itpp-labs/sync-addons/pull/219

**Comment by yelizariev** [comment]
- [x] https://github.com/itpp-labs/sync-addons/pull/166

**Comment by mentalko** [comment]
https://github.com/itpp-labs/sync-addons/pull/269

**Comment by yelizariev** [comment]
https://github.com/itpp-labs/sync-addons/pull/270
