### ISSUE TITLE
how to use postman to consume this endpoint 

### ISSUE THREAD

**Issue by ericdai** [itpp-labs/sync-addons#251]
I want to use postman to test this endpoint ,but did not
find how to config it

**Comment by Gokulakannanaj** [comment]
@yelizariev @trojikman  - Could you help?

**Comment by yelizariev** [comment]
I don't use postman. 
You could sponsor making such a research and updating the docs. 
https://www.patreon.com/itpp

**Comment by juliendelrio** [comment]
You just have to create a request.

Set your url with the endpoint given by openapi.

Set Basic Auth :
- username : the database name
- password : the user token

For patch requests : body as raw/json
