### ISSUE TITLE
[14.0] Failed to fetch the response

### ISSUE THREAD

**Issue by Gokulakannanaj** [itpp-labs/sync-addons#259]
I'm getting the following error in V14.

![Undocumented Error](https://user-images.githubusercontent.com/41570711/120313543-c2739f00-c2f7-11eb-8f1c-e4adfd63f882.png)

**No Errors in the Logger**
2021-06-01 11:08:45,375 11544 INFO ? werkzeug: 127.0.0.1 - - [01/Jun/2021 11:08:45] "OPTIONS /api/v1/mobile/res.partner HTTP/1.1" 405 - 1 0.003 0.006

**Note:**  Configured the --load openapi,base,web and Authorization have done based on the Documentation.

**Comment by trojikman** [comment]
Hi,
check these docs https://github.com/itpp-labs/sync-addons/blob/14.0/openapi/doc/index.rst#swagger-editor

**Comment by Gokulakannanaj** [comment]
@trojikman - Thanks for the Update. I read the document. Could you help me to configure that code in the local env?
Thanks in Advance.

**Comment by trojikman** [comment]
You need Nginx to configure it, we can provide technical support via subscription (you can check the details here https://www.patreon.com/itpp). For more information write us via e-mail: help@itpp.dev
