### ISSUE TITLE
sync_telegram: can't unsubscribe the channel

### ISSUE THREAD

**Issue by trojikman** [itpp-labs/sync-addons#277]
**Steps to reproduce the issue:**

1. Send a message to the bot via Telegram
2. Recieve message via Discuss in Odoo 
3. Click on the cross to unsubscribe from the channel
4. Refresh the page 
Result: We still see the channel and still subscribed to it

**Expected behavior:**  be able to unsubscribe from the channel

https://user-images.githubusercontent.com/23641186/123621815-0c7f7000-d825-11eb-8dc4-26ecd635b035.mp4

**Comment by yelizariev** [comment]
Это специально делал, т.к. иначе не понятно где можно посмотреть все каналы. Надо продумать как делать

https://github.com/itpp-labs/sync-addons/blob/97153f30a1bac09156961c42b8e6a8697f22fdb2/sync_telegram/models/mail/mail_channel.py#L22-L25

**Comment by yelizariev** [comment]
Как вариант, можно сделать дело https://github.com/itpp-labs/sync-addons/issues/312 и вернуть фильтр is_pinned
