### ISSUE TITLE
sync_telegram: get lib importing out of try-block

### ISSUE THREAD

**Issue by yelizariev** [itpp-labs/sync-addons#294]
it was copy-pasted from `sync` module, where telegram is demo and we don't require to installing telegram package  
https://github.com/itpp-labs/sync-addons/blob/a295ccaef1df974771dfa1267c5a2103385e172a/sync_telegram/models/sync_project.py#L39-L46
* no need for try-block
* no need to disable pylint
* no need to put importing inside `_eval_context_telegram` method. 

  * The same about other imports:

   https://github.com/itpp-labs/sync-addons/blob/a295ccaef1df974771dfa1267c5a2103385e172a/sync_telegram/models/sync_project.py#L35-L37 
  * The same about constants:
   https://github.com/itpp-labs/sync-addons/blob/a295ccaef1df974771dfa1267c5a2103385e172a/sync_telegram/models/sync_project.py#L50-L53

**Comment by yelizariev** [comment]
@mentalko

**Comment by mentalko** [comment]
Про pylint не понял

**Comment by trojikman** [comment]
> Про pylint не понял

Об этой строке речь:
https://github.com/itpp-labs/sync-addons/blob/a295ccaef1df974771dfa1267c5a2103385e172a/sync_telegram/models/sync_project.py#L41

С помощью этого комментария отключается проверка. Если ты этот комментарий уберёшь, то пре коммит начнёт ругаться
