### ISSUE TITLE
sync_telegram, sync: change telegram lib

### ISSUE THREAD

**Issue by yelizariev** [itpp-labs/sync-addons#295]
Use this one instead https://github.com/eternnoir/pyTelegramBotAPI

The current lib is too heavy and we don't need all those features

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/22/21 - 08/22/21
Work session total: 0:21:06
Billable: Yes

Grand total: 0:21:06

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/23/21 - 08/23/21
Work session total: 2:51:07
Billable: Yes

Grand total: 3:12:13

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/24/21 - 08/24/21
Work session total: 2:34:44
Billable: Yes

Grand total: 5:46:57

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/25/21 - 08/25/21
Work session total: 2:05:29
Billable: Yes

Grand total: 7:52:26

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/02/21 - 09/02/21
Work session total: 0:56:05
Billable: Yes

Grand total: 8:48:31
