### ISSUE TITLE
sync: return missing fix

### ISSUE THREAD

**Issue by mentalko** [itpp-labs/sync-addons#298]
повторное исправление https://github.com/trojikman/sync-addons/commit/f7beb3b5ef9bc6060d96dba744d2f412d962449a , т.к. после форвардпортирование то обновление пропало https://github.com/mentalko/sync-addons/commit/3c2711324ac041104841722098646bd050bad807

**Comment by mentalko** [comment]
re-fix of https://github.com/trojikman/sync-addons/commit/f7beb3b5ef9bc6060d96dba744d2f412d962449a as after forward porting that update was lost  https://github.com/mentalko/sync-addons/commit/3c2711324ac041104841722098646bd050bad807

**Comment by yelizariev** [comment]
It's obsolete after https://github.com/itpp-labs/sync-addons/commit/39f001bec5f4ccfeb7ef4742d382dcb3ea7c0b25
