### ISSUE TITLE
sync_odoo2odoo

### ISSUE THREAD

**Issue by yelizariev** [itpp-labs/sync-addons#304]
Make a separate module similar to a demo project in `sync` module

Eval context should have new methods similar to sync helpers https://github.com/itpp-labs/sync-addons/blob/e924974e60ba40fbc7b700a96b1d95b9932e3640/sync/doc/index.rst#sync-helpers 

`sync_odoo2odoo_push(model_name, domain=None, fields=None, active_test=True, create=False, update=False)`
`sync_odoo2odoo_pull(model_name, domain=None, fields=None, active_test=True, create=False, update=False)`

* `create`: boolean value for "create record if it doesn't exist"
* `update`: boolean value for "update record if it exists"
* `domain`: which records of `model_name` to sync
* `fields`: which fields to sync
* `active_test`: value to pass to context on reading

**Comment by mentalko** [comment]
self.with_context(active_test=False).search


all_partners_and_children[partner] = self.with_context(active_test=False).search([('id', 'child_of', partner.id)]).ids

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/05/21 - 08/05/21
Work session total: 2:26:25
Billable: Yes

Grand total: 2:26:25

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/06/21 - 08/06/21
Work session total: 2:40:28
Billable: Yes

Grand total: 5:06:53

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/08/21 - 08/08/21
Work session total: 2:28:02
Billable: Yes

Grand total: 7:34:55

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/09/21 - 08/09/21
Work session total: 0:46:44
Billable: Yes

Grand total: 8:21:39

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/10/21 - 08/10/21
Work session total: 2:50:51
Billable: Yes

Grand total: 11:12:30

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/12/21 - 08/12/21
Work session total: 0:45:59
Billable: Yes

Grand total: 11:58:29

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/13/21 - 08/13/21
Work session total: 1:17:32
Billable: Yes

Grand total: 13:16:01

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/14/21 - 08/14/21
Work session total: 2:00:04
Billable: Yes

Grand total: 15:16:05

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/13/21 - 08/13/21
Work session total: 0:00:04
Billable: Yes

Grand total: 15:16:09

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/17/21 - 08/17/21
Work session total: 0:14:49
Billable: Yes

Grand total: 15:30:58

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/21/21 - 08/21/21
Work session total: 1:10:34
Billable: Yes

Grand total: 16:41:32

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/25/21 - 08/25/21
Work session total: 0:49:08
Billable: Yes

Grand total: 17:30:40

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/02/21 - 09/02/21
Work session total: 0:48:29
Billable: Yes

Grand total: 18:19:09

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/03/21 - 09/03/21
Work session total: 0:15:14
Billable: Yes

Grand total: 18:34:23

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/04/21 - 09/04/21
Work session total: 1:57:39
Billable: Yes

Grand total: 20:32:02

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/05/21 - 09/05/21
Work session total: 0:03:10
Billable: Yes

Grand total: 20:35:12

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/08/21 - 09/08/21
Work session total: 0:05:00
Billable: Yes

Grand total: 20:40:12
