### ISSUE TITLE
sync_viber: sending files

### ISSUE THREAD

**Issue by trojikman** [itpp-labs/sync-addons#309]
The module is located here: https://github.com/itpp-labs/sync-addons/tree/14.0/sync_viber
Similar to [sync_telegram](https://github.com/itpp-labs/sync-addons/tree/14.0/sync_telegram) we need the ability to send and receive files, emojis, etc.

**Comment by yelizariev** [comment]
The module already has a placeholder and copy-pasted code from sync_telegram module:

https://github.com/itpp-labs/sync-addons/blob/42bb88abf139652a1fb4689ccb72fed6a3fc5bd2/sync_viber/data/sync_project_data.xml#L210-L223

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/17/21 - 08/17/21
Work session total: 0:12:21
Billable: Yes

Grand total: 0:12:21

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/18/21 - 08/18/21
Work session total: 2:21:24
Billable: Yes

Grand total: 2:33:45

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/19/21 - 08/19/21
Work session total: 2:32:08
Billable: Yes

Grand total: 5:05:53

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/24/21 - 08/24/21
Work session total: 0:00:04
Billable: Yes

Grand total: 5:05:57

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/01/21 - 09/01/21
Work session total: 2:16:15
Billable: Yes

Grand total: 7:22:12

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/03/21 - 09/03/21
Work session total: 0:18:37
Billable: Yes

Grand total: 7:40:49

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/04/21 - 09/04/21
Work session total: 0:31:45
Billable: Yes

Grand total: 8:12:34

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/05/21 - 09/05/21
Work session total: 0:55:05
Billable: Yes

Grand total: 9:07:39

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/05/21 - 09/05/21
Work session total: 0:03:57
Billable: Yes

Grand total: 9:11:36

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/07/21 - 09/07/21
Work session total: 1:51:11
Billable: Yes

Grand total: 11:02:47

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/10/21 - 09/10/21
Work session total: 0:20:01
Billable: Yes

Grand total: 11:22:48

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/12/21 - 09/12/21
Work session total: 0:02:52
Billable: Yes

Grand total: 11:25:40

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/13/21 - 09/13/21
Work session total: 0:41:52
Billable: Yes

Grand total: 12:07:32

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/16/21 - 09/16/21
Work session total: 0:19:14
Billable: Yes

Grand total: 12:26:46

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/17/21 - 09/17/21
Work session total: 1:06:53
Billable: Yes

Grand total: 13:33:39
