### ISSUE TITLE
Sync Studio: DB Trigger starts tasks immediately

### ISSUE THREAD

**Issue by schiggi** [itpp-labs/sync-addons#323]
Hey there,

Reading the [docs](https://github.com/itpp-labs/sync-addons/blob/14.0/sync/doc/index.rst#id2), I was under the impression that db triggered tasks are added to the queue job before being executed.

From tests, this seems not to be the case. Looking at these 2 lines [#1](https://github.com/itpp-labs/sync-addons/blob/c2f0941660b8ae99e368084f760973654418b05e/sync/models/sync_trigger_automation.py#L19) 
and [#2](https://github.com/itpp-labs/sync-addons/blob/c2f0941660b8ae99e368084f760973654418b05e/sync/models/sync_task.py#L104), it seems with_delay is not set. 

But maybe I am missing something. Would be happy to understand if I am doing sth wrong.

**Comment by trojikman** [comment]
Thank you for the feedback @schiggi ! We'll add `withe_dealy=True` here https://github.com/itpp-labs/sync-addons/blob/c2f0941660b8ae99e368084f760973654418b05e/sync/models/sync_trigger_automation.py#L21

**Comment by yelizariev** [comment]
You are right, 
I noticed this behavior before, but didn't investigate and didn't check that the docs states opposite.
I even did a workaround in sync_viber module: 
https://github.com/itpp-labs/sync-addons/blob/c2f0941660b8ae99e368084f760973654418b05e/sync_viber/data/sync_project_data.xml#L204

Though we just need to add `with_delay=True` here:

https://github.com/itpp-labs/sync-addons/blob/c2f0941660b8ae99e368084f760973654418b05e/sync/models/sync_trigger_automation.py#L21

Thanks for pointing to the problem!

**Comment by trojikman** [comment]
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/24/21 - 08/24/21
Work session total: 1:39:18
Billable: Yes

Grand total: 1:39:18

**Comment by trojikman** [comment]
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/01/21 - 09/01/21
Work session total: 2:36:23
Billable: Yes

Grand total: 4:15:41

**Comment by trojikman** [comment]
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/01/21 - 09/01/21
Work session total: 0:17:40
Billable: Yes

Grand total: 4:33:21
