### ISSUE TITLE
Missing field "Trigger fields" in custom DB Trigger interface

### ISSUE THREAD

**Issue by schiggi** [itpp-labs/sync-addons#325]
Hello,

If I am adding or editing a db trigger via Sync Studio, I am missing the default _Trigger field_, which is very useful.
Default Odoo Automated Actions
![image](https://user-images.githubusercontent.com/3776606/130664914-21125c08-8eb4-4e75-88ac-3967a2feef40.png)
Sync Studio
![image](https://user-images.githubusercontent.com/3776606/130665016-a8a60b49-8e6b-47a0-8a29-4b7a900a933a.png)

**Comment by mentalko** [comment]
via Hubstaff
User: ilya ilchenko

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/26/21 - 08/26/21
Work session total: 2:04:12
Billable: Yes

Grand total: 2:04:12
