### ISSUE TITLE
sync_telegram, sync_viber: access error while leaving the channel

### ISSUE THREAD

**Issue by trojikman** [itpp-labs/sync-addons#327]
Steps to reproduce the error:
1) Write to the bot
2) Receive the message in Odoo and go to Telegram/Viber channels through Discuss sidebar.
3) Press the Leave button
As a result, you'll get "Access Error":
![Screenshot from 2021-08-26 13-49-09](https://user-images.githubusercontent.com/23641186/130932370-83526df9-46d9-47c1-b73b-4aa23bc5d757.png)

Also, when trying to send a new message to the bot the message in Odoo doesn't appear

Expected behavior:
Don't get an error and be able to receive messages from archived messages

**Comment by em230418** [comment]
via Hubstaff
User: Eugene Molotov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/01/21 - 09/01/21
Work session total: 1:05:50
Billable: Yes

Grand total: 1:05:50

**Comment by trojikman** [comment]
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/02/21 - 09/02/21
Work session total: 0:16:40
Billable: Yes

Grand total: 2:35:18

**Comment by em230418** [comment]
via Hubstaff
User: Eugene Molotov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/02/21 - 09/02/21
Work session total: 1:12:48
Billable: Yes

Grand total: 2:35:18

**Comment by em230418** [comment]
via Hubstaff
User: Eugene Molotov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/07/21 - 09/07/21
Work session total: 0:56:57
Billable: Yes

Grand total: 3:32:15

**Comment by trojikman** [comment]
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/08/21 - 09/08/21
Work session total: 0:14:52
Billable: Yes

Grand total: 4:27:09

**Comment by em230418** [comment]
via Hubstaff
User: Eugene Molotov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/08/21 - 09/08/21
Work session total: 0:40:02
Billable: Yes

Grand total: 4:27:09
