### ISSUE TITLE
openapi: API Token regenerated randomly

### ISSUE THREAD

**Issue by juliendelrio** [itpp-labs/sync-addons#352]
Hi,

I use REST API/OpenAPI/Swagger 14.

It seems that the Api Token associated to my user is frequently regenerated. I don't understand why. It's breaking my other server using this token.

I can for the api token and write the previous value, but it's not very confortable.

Do you have any idea to prevent it ?

**Comment by yelizariev** [comment]
I never heard about this problem. Sorry

**Comment by juliendelrio** [comment]
We changed our hosting service and the problem stopped.
Very weird.
I close the issue.
