### ISSUE TITLE
OCA connector comparison

### ISSUE THREAD

**Issue by amon-ra** [itpp-labs/sync-addons#354]
Hello.
I think it could be a good idea to add a little comparison from this framework to oca connector.

I am starting a new project and I don't know wich framework to use.

Thanks in advice

**Comment by yelizariev** [comment]
Hello!

You could check this presentation https://itpp.dev/sync-studio

**Comment by amon-ra** [comment]
This project has a more modern approach and is simpler to use. Close for now
