### ISSUE TITLE
open api [13.0] - openapi_token not unique

### ISSUE THREAD

**Issue by CasVissers-360ERP** [itpp-labs/sync-addons#74]
When installing the module on a database with multiple users, all users get the same openapi_token which results in a singleton error when making an API call.

I think the openapi_token should get a unqiue contraint and in addition the token should be regenerated per user when getting the default token, or a token should only be created on request?

@aschenkels-ictstudio

**Comment by yelizariev** [comment]
There is already a check generate unique token...

https://github.com/it-projects-llc/sync-addons/blob/72636b4/openapi/models/res_users.py#L23-L27

My bet that it doesn't work in v 13.0 due to optimization made there... I'll check it, maybe adding ``self.flush()`` will help.

**Comment by yelizariev** [comment]
Maybe calling ``reset_all_openapi_tokens`` after installation is enough to fix...

@CasVissers could you take a look on #75
