### ISSUE TITLE
[13.0][OpenAPI] One2many not working

### ISSUE THREAD

**Issue by CasVissers-360ERP** [itpp-labs/sync-addons#79]
Whenever I use a one2many I seem to be stuck on:

can't adapt type 'dict'

This is the json I use:```

{
"name": "Stock Count",
"line_ids": [
{
"product_id": 1513,
"location_id": 541,
"inventory_id": 1
}
],
"state": "confirm",
"start_empty": "True"
}

```
I want to create a stock inventory with new lines in the same post.

**Comment by fedoranvar** [comment]
Questions:

* How you send request? (Postman, curl, Swagger etc.)
* What method? (POST, PATCH ? )
* What Model ? (stock.move ?)
* What Function? (create, write, unlink etc.)
* What response you receive?
*

**Comment by CasVissers-360ERP** [comment]
- How you send request? (Postman, curl, Swagger etc.)
Postman
- What method? (POST, PATCH ? )
Post
- What Model ? (stock.move ?)
stock.inventory
- What Function? (create, write, unlink etc.)
create (with one2many lines)
- What response you receive?
{
    "error": "ProgrammingError",
    "error_descrip": "can't adapt type 'dict'"
}

**Comment by CasVissers-360ERP** [comment]
@fedoranvar 
More context:
I'm trying to create an inventory count with about 700 lines. I want to creates the lines in the same post (it would be very inefficient to make 701 posts). 

If I post without the o2m everything works fine, if I add the o2m I get the "can't adapt type dict"  error. In the log I see that Odoo is failing because it's trying to do a select on inventory.line. While I think it should be creating new lines?

**Comment by CasVissers-360ERP** [comment]
@fedoranvar 
Any update here?

**Comment by fedoranvar** [comment]
@CasVissers 

Sorry for delay

Try build request using this article:

https://odoo-development.readthedocs.io/en/latest/dev/py/x2many.html

so, for example (to create and add x2many-object):
{
"x2many-field": [
[0,0,{
"field_1": <value_1>
}]
]
}

**Comment by fedoranvar** [comment]
@CasVissers 

Sorry for delay

Try build request using this article:
https://odoo-development.readthedocs.io/en/latest/dev/py/x2many.html

so, for example (to create and add x2many-object):
{
"x2many-field": [
[0,0,{
"field_1": <value_1>
}]
]
}

**Comment by CasVissers** [comment]
@fedoranvar 
Yes we tried with:
```
{
    "name": "Stock Count",
	"line_ids": [0, 0, {"product_id": 1513, "location_id": 1, "inventory_id": 4}] ,
    "state": "confirm",
    "start_empty": "True"
}
```
Response:
```
{
    "error": "ProgrammingError",
    "error_descrip": "can't adapt type 'dict'"
}
```

**Comment by CasVissers-360ERP** [comment]
Thanks, issue solved!
